### ISSUE TITLE
KadViewer: printen van Ruimtelijke Plannen laag werkt niet

### ISSUE THREAD

**Issue by justb4** [map5nl/map5#31]
## Scenario

* open `KadViewer`
* zet de laag `Ruimtelijke Plannen | Bestemmingsplannen (ROO)` aan
* klik Print icoon, maak print

## Verwachting

* PDF print opent met Ruimtelijke Plannen over OpenTopo kaart

## Werkelijkheid

* PDF print opent met alleen OpenTopo kaart

## Probleem

* iets met certificaten naar ROO server vanuit Print server

Melding vanuit Print server:

```
2019-04-26 14:55:57,727 [tilesReader80] DEBUG     org.mapfish.print.PDFUtils - loading image: https://s.map5.nl/map/justobj.1998mj/tms/1.0.0/opentopo/EPSG28992/06/30/32.jpeg
2019-04-26 14:55:57,727 [tilesReader68] DEBUG     org.mapfish.print.PDFUtils - loading image: https://s.map5.nl/map/justobj.1998mj/tms/1.0.0/opentopo/EPSG28992/06/31/32.jpeg
2019-04-26 14:55:57,727 [tilesReader71] DEBUG     org.mapfish.print.PDFUtils - loading image: https://s.map5.nl/map/justobj.1998mj/tms/1.0.0/opentopo/EPSG28992/06/31/33.jpeg
2019-04-26 14:55:57,727 [tilesReader77] DEBUG     org.mapfish.print.PDFUtils - loading image: https://s.map5.nl/map/justobj.1998mj/tms/1.0.0/opentopo/EPSG28992/06/30/33.jpeg
2019-04-26 14:55:57,729 [tilesReader70] DEBUG     org.mapfish.print.PDFUtils - loading image: https://afnemers.ruimtelijkeplannen.nl/afnemers2012/services?BBOX=138610.14510645013%2C473857.64510644967%2C145753.8948935498%2C481001.3948935504&HEIGHT=116&WIDTH=116&TRANSPARENT=true&map_resolution=75&VERSION=1.1.1&FORMAT=image%2Fpng&SERVICE=WMS&format_options=dpi%3A75&LAYERS=BP%3AHuidigeBestemming&REQUEST=GetMap&STYLES=&DPI=75&SRS=EPSG%3A28992
2019-04-26 14:55:57,774 [tilesReader70] ERROR     org.mapfish.print.PDFUtils - Server returned an error for https://afnemers.ruimtelijkeplannen.nl/afnemers2012/services?BBOX=138610.14510645013%2C473857.64510644967%2C145753.8948935498%2C481001.3948935504&HEIGHT=116&WIDTH=116&TRANSPARENT=true&map_resolution=75&VERSION=1.1.1&FORMAT=image%2Fpng&SERVICE=WMS&format_options=dpi%3A75&LAYERS=BP%3AHuidigeBestemming&REQUEST=GetMap&STYLES=&DPI=75&SRS=EPSG%3A28992: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
2019-04-26 14:55:57,779 [tilesReader68] DEBUG     org.mapfish.print.PDFUtils - loaded image: https://s.map5.nl/map/justobj.1998mj/tms/1.0.0/opentopo/EPSG28992/06/31/32.jpeg
2019-04-26 14:55:57,779 [tilesReader77] DEBUG     org.mapfish.print.PDFUtils - loaded image: https://s.map5.nl/map/justobj.1998mj/tms/1.0.0/opentopo/EPSG28992/06/30/33.jpeg
2019-04-26 14:55:57,780 [tilesReader80] DEBUG     org.mapfish.print.PDFUtils - loaded image: https://s.map5.nl/map/justobj.1998mj/tms/1.0.0/opentopo/EPSG28992/06/30/32.jpeg
2019-04-26 14:55:57,783 [tilesReader71] DEBUG     org.mapfish.print.PDFUtils - loaded image: https://s.map5.nl/map/justobj.1998mj/tms/1.0.0/opentopo/EPSG28992/06/31/33.jpeg
2019-04-26 14:55:57,783 [tilesReader71] ERROR .mapfish.print.PDFCustomBlocks - Error while adding a PDF element
java.io.IOException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.mapfish.print.PDFUtils.handleImageLoadError(PDFUtils.java:357)
	at org.mapfish.print.PDFUtils.loadImageFromUrl(PDFUtils.java:341)
	at org.mapfish.print.PDFUtils.getImageDirect(PDFUtils.java:182)
	at org.mapfish.print.PDFUtils.getImage(PDFUtils.java:102)
	at org.mapfish.print.PDFUtils.getImage(PDFUtils.java:86)
	at org.mapfish.print.map.renderers.BitmapTileRenderer$1.readTile(BitmapTileRenderer.java:73)
	at org.mapfish.print.map.MapTileTask.process(MapTileTask.java:41)
	at org.mapfish.print.map.MapTileTask.process(MapTileTask.java:33)
	at org.pvalsecc.concurrent.OrderedResultsExecutor$Runner.run(OrderedResultsExecutor.java:186)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by justb4** [comment]
## Oplossing (ook voor #31)
Zie https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ

Certificaat dient aan `cacerts` bestand van de Java VM van de print server (Tomcat) toegevoegd te worden, als volgt:

* in Firefox, ga naar Plannen URL bijv https://afnemers.ruimtelijkeplannen.nl/afnemers2012/services?
* klik op "slotje"
* bekijk details certificaat, klik door naar "Export..."
* download certificaat 
* installeer in Java: `keytool -import -alias ruimtelijke_plannen  -keystore /usr/lib/jvm/java-7-oracle/jre/lib/security/cacerts -file afnemers_ruimtelijkeplannen_nl.crt `
* herstart VM
* print met ROO laag lukt nu wel!
