### ISSUE TITLE
KadViewer: printen van PDOK lagen  werkt niet

### ISSUE THREAD

**Issue by justb4** [map5nl/map5#32]
Zelfde soort issue als #31.

## Scenario

* open `KadViewer`
* zet een PDOK laag aan bijv `Bodemkaart`
* klik Print icoon, maak print

## Verwachting

* PDF print opent met Bodemkaart over OpenTopo kaart

## Werkelijkheid

* PDF print opent met alleen OpenTopo kaart en text bericht linksonder

## Probleem

* iets met certificaten naar PDOK server vanuit Print server

Melding vanuit Print server:

```
sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
.
.
java.io.IOException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at org.mapfish.print.PDFUtils.handleImageLoadError(PDFUtils.java:357)
	at org.mapfish.print.PDFUtils.loadImageFromUrl(PDFUtils.java:341)
	at org.mapfish.print.PDFUtils.getImageDirect(PDFUtils.java:182)
	at org.mapfish.print.PDFUtils.getImage(PDFUtils.java:102)
	at org.mapfish.print.PDFUtils.getImage(PDFUtils.java:86)
	at org.mapfish.print.map.renderers.BitmapTileRenderer$1.readTile(BitmapTileRenderer.java:73)
	at org.mapfish.print.map.MapTileTask.process(MapTileTask.java:41)
	at org.mapfish.print.map.MapTileTask.process(MapTileTask.java:33)
	at org.pvalsecc.concurrent.OrderedResultsExecutor$Runner.run(OrderedResultsExecutor.java:186)
	at java.lang.Thread.run(Thread.java:745)
```

## Oplossing (ook voor #31)
Zie https://stackoverflow.com/questions/21076179/pkix-path-building-failed-and-unable-to-find-valid-certification-path-to-requ

Certificaat dient aan `cacerts` bestand van de Java VM van de print server (Tomcat) toegevoegd te worden, als volgt:

* in Firefox, ga naar PDK URL bijv https://geodata.nationaalgeoregister.nl/rdinfo/wms?
* klik op "slotje"
* bekijk details certificaat, klik door naar "Export..."
* download certificaat 
* installeer in Java: `keytool -import -alias example -keystore /usr/lib/jvm/java-7-oracle/jre/lib/security/cacerts -file geodata_nationaalgeoregister_nl.crt`
* herstart VM
* print met PDOK laag lukt nu wel!

**Comment by justb4** [comment]
Opgelost!
